### ISSUE TITLE
Cannot compile sql query for constants

### ISSUE THREAD

**Issue by domoritz** [uwescience/raco#380]
If I want to push initial work into sql for this query:

```python
P = scan(public:adhoc:TwitterK);
PP = [from P emit 3 as three];
store(PP, Test);
```

it fails

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/myria_web_main.py", line 517, in post
    self.get()
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/myria_web_main.py", line 495, in get
    push_sql=push_sql)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/myria_web_main.py", line 124, in get_physical_plan
    multiway_join=multiway_join, push_sql=push_sql)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/myria_web_main.py", line 110, in get_plan
    push_sql=push_sql)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/myrial/interpreter.py", line 419, in get_physical_plan
    return self.__get_physical_plan_for__(target_phys_algebra, **kwargs)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/myrial/interpreter.py", line 408, in __get_physical_plan_for__
    return optimize(logical_plan, **kwargs)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/compile.py", line 64, in optimize
    return optimize_by_rules(expr, target.opt_rules(**kwargs))
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/compile.py", line 53, in optimize_by_rules
    expr = recursiverule(expr)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/compile.py", line 44, in recursiverule
    newe = rule(e)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/rules.py", line 19, in __call__
    return self.fire(expr)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/language/myrialang.py", line 1230, in fire
    sql_plan = cat.get_sql(expr)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/language/sql/catalog.py", line 181, in get_sql
    return self._get_unary_sql(plan)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/language/sql/catalog.py", line 131, in _get_unary_sql
    input = self.get_sql(plan.input).alias("input")
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/language/sql/catalog.py", line 181, in get_sql
    return self._get_unary_sql(plan)
  File "/base/data/home/apps/s~myria-web/1.380988297246986780/raco/language/sql/catalog.py", line 141, in _get_unary_sql
    for (name, e) in plan.emitters]
AttributeError: 'int' object has no attribute 'label'
```

**Comment by dhalperi** [comment]
confirmed.

fix aspect 1: make sure the push-into-sql failure detection catches this error. it will not be pushed down, but it should fall back to the in-myria implementation.

fix aspect 2: make it push down correctly.
