### ISSUE TITLE
IndexError thrown from PushIntoSQL rule

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#497]
When executing a self-join against a relation partitioned on the join key, raco throws an `IndexError` while applying the `PushIntoSQL` rule:

```
Traceback (most recent call last):
  File "/opt/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/mnt/myria-web/appengine/myria_web_main.py", line 475, in post
    self.get()
  File "/mnt/myria-web/appengine/myria_web_main.py", line 453, in get
    push_sql=push_sql)
  File "/mnt/myria-web/appengine/myria_web_main.py", line 124, in get_physical_plan
    multiway_join=multiway_join, push_sql=push_sql)
  File "/mnt/myria-web/appengine/myria_web_main.py", line 110, in get_plan
    push_sql=push_sql)
  File "/mnt/myria-web/appengine/raco/myrial/interpreter.py", line 451, in get_physical_plan
    return self.__get_physical_plan_for__(target_phys_algebra, **kwargs)
  File "/mnt/myria-web/appengine/raco/myrial/interpreter.py", line 440, in __get_physical_plan_for__
    return optimize(logical_plan, **kwargs)
  File "/mnt/myria-web/appengine/raco/compile.py", line 70, in optimize
    return optimize_by_rules(expr, target.opt_rules(**kwargs))
  File "/mnt/myria-web/appengine/raco/compile.py", line 59, in optimize_by_rules
    expr = recursiverule(expr)
  File "/mnt/myria-web/appengine/raco/compile.py", line 44, in recursiverule
    newe = rule(e)
  File "/mnt/myria-web/appengine/raco/rules.py", line 31, in __call__
    return self.fire(expr)
  File "/mnt/myria-web/appengine/raco/backends/myria/myria.py", line 1509, in fire
    sql_plan = cat.get_sql(expr)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 203, in get_sql
    return self._get_unary_sql(plan)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 146, in _get_unary_sql
    input = self.get_sql(plan.input).alias("input")
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 203, in get_sql
    return self._get_unary_sql(plan)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 146, in _get_unary_sql
    input = self.get_sql(plan.input).alias("input")
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 203, in get_sql
    return self._get_unary_sql(plan)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 151, in _get_unary_sql
    cond = self._convert_expr(cols, plan.condition, input_sch)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 76, in _convert_expr
    return self._convert_unary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 108, in _convert_unary_expr
    input = self._convert_expr(cols, expr.input, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 117, in _convert_binary_expr
    right = self._convert_expr(cols, expr.right, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 72, in _convert_expr
    return self._convert_attribute_ref(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 95, in _convert_attribute_ref
    return cols[expr.position]
IndexError: list index out of range
```

Source query (requires the `tipsy` branch, error occurs while evaluating the relation `local`):

```
const partition: 0.5;
const epsilon: 0.0000106;

def mod(x, n): x - int(x/n)*n;
def cell(v): int((v - mod(v, partition)) * (1/partition));
def is_ghost(xoffset, yoffset, zoffset):
  case when xoffset = 0 and
            yoffset = 0 and
            zoffset = 0 then 0 else 1 end;
def is_replicated(x, y, z, xoffset, yoffset, zoffset):
  is_ghost(xoffset, yoffset, zoffset) = 0 or
  cell(x + epsilon*xoffset) != cell(x) or
  cell(y + epsilon*yoffset) != cell(y) or
  cell(z + epsilon*zoffset) != cell(z);
def distance(x1, x2, y1, y2, z1, z2): sqrt((x1-x2)*(x1-x2) +
                                           (y1-y2)*(y1-y2) +
                                           (z1-z2)*(z1-z2));

points = load("https://s3-us-west-2.amazonaws.com/uwdb/sampleData/sampleTipsy/cosmo8.33PLK.256g3bwK1C52.000970", tipsy(group="amiga"));
store(points, Cosmo8_points, [iOrder]);

permutations = load("https://s3-us-west-2.amazonaws.com/myria/permutations",
                    csv(schema(xoffset:int,
                               yoffset:int,
                               zoffset:int), skip=0));
store(permutations, Cosmo8_permutations);

points = scan(public:adhoc:Cosmo8_points);
permutations = scan(public:adhoc:Cosmo8_permutations);

-- Partition into a grid with edges of size partition
-- Replicate any point that falls within epsilon of a partition boundary

partitions = [from points, permutations
              where is_replicated(x, y, z, xoffset, yoffset, zoffset)
              emit iOrder as id, x, y, z,
                   cell(x) + xoffset as px,
                   cell(y) + yoffset as py,
                   cell(z) + zoffset as pz,
                   is_ghost(xoffset, yoffset, zoffset) as ghost];

store(partitions, Cosmo8_partitions, [px, py, pz]);

partitions = scan(public:adhoc:Cosmo8_partitions);

-- Cross product on partition + ghost cells; no shuffle required
local = [from partitions left,
              partitions right
         where left.px = right.px and
               left.py = right.py and
               left.pz = right.pz
         emit *];

-- Calculate distances within each local pair and filter outliers
distances = [from local
             where id < id1 and
                   ghost = 0 and
                   distance(x, x1, y, y1, z, z1) <= epsilon
             emit id as id1,
                  id1 as id2,
                  distance(x, x1, y, y1, z, z1) as distance];

store(distances, Cosmo8_distances);
```

**Comment by BrandonHaynes** [comment]
I *think* this is a regression issue, where the workaround was to explicitly name the attributes emitted when forming `local`.

**Comment by senderista** [comment]
I tried this workaround and still get the same error:

```
partitions = scan(public:adhoc:Cosmo8_partitions);

-- Cross product on partition + ghost cells; no shuffle required
local = [from partitions left,
              partitions right
         where left.px = right.px and
               left.py = right.py and
               left.pz = right.pz
         emit left.id as id1, right.id as id2,
         left.x as x1, left.y as y1, left.z as z1,
         right.x as x2, right.y as y2, right.z as z2,
         left.ghost as ghost];

-- Calculate distances within each local pair and filter outliers
distances = [from local
             where id1 < id2 and
                   ghost = 0 and
                   distance(x1, x2, y1, y2, z1, z2) <= epsilon
             emit id1 as id1,
                  id2 as id2,
                  distance(x1, x2, y1, y2, z1, z2) as distance];

store(distances, Cosmo8_distances);
```

```
Traceback (most recent call last):
  File "/opt/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/mnt/myria-web/appengine/myria_web_main.py", line 475, in post
    self.get()
  File "/mnt/myria-web/appengine/myria_web_main.py", line 453, in get
    push_sql=push_sql)
  File "/mnt/myria-web/appengine/myria_web_main.py", line 124, in get_physical_plan
    multiway_join=multiway_join, push_sql=push_sql)
  File "/mnt/myria-web/appengine/myria_web_main.py", line 110, in get_plan
    push_sql=push_sql)
  File "/mnt/myria-web/appengine/raco/myrial/interpreter.py", line 451, in get_physical_plan
    return self.__get_physical_plan_for__(target_phys_algebra, **kwargs)
  File "/mnt/myria-web/appengine/raco/myrial/interpreter.py", line 440, in __get_physical_plan_for__
    return optimize(logical_plan, **kwargs)
  File "/mnt/myria-web/appengine/raco/compile.py", line 70, in optimize
    return optimize_by_rules(expr, target.opt_rules(**kwargs))
  File "/mnt/myria-web/appengine/raco/compile.py", line 59, in optimize_by_rules
    expr = recursiverule(expr)
  File "/mnt/myria-web/appengine/raco/compile.py", line 44, in recursiverule
    newe = rule(e)
  File "/mnt/myria-web/appengine/raco/rules.py", line 31, in __call__
    return self.fire(expr)
  File "/mnt/myria-web/appengine/raco/backends/myria/myria.py", line 1509, in fire
    sql_plan = cat.get_sql(expr)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 203, in get_sql
    return self._get_unary_sql(plan)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 146, in _get_unary_sql
    input = self.get_sql(plan.input).alias("input")
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 203, in get_sql
    return self._get_unary_sql(plan)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 146, in _get_unary_sql
    input = self.get_sql(plan.input).alias("input")
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 203, in get_sql
    return self._get_unary_sql(plan)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 151, in _get_unary_sql
    cond = self._convert_expr(cols, plan.condition, input_sch)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 76, in _convert_expr
    return self._convert_unary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 108, in _convert_unary_expr
    input = self._convert_expr(cols, expr.input, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 116, in _convert_binary_expr
    left = self._convert_expr(cols, expr.left, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 78, in _convert_expr
    return self._convert_binary_expr(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 117, in _convert_binary_expr
    right = self._convert_expr(cols, expr.right, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 72, in _convert_expr
    return self._convert_attribute_ref(cols, expr, input_scheme)
  File "/mnt/myria-web/appengine/raco/backends/sql/catalog.py", line 95, in _convert_attribute_ref
    return cols[expr.position]
IndexError: list index out of range
```

**Comment by senderista** [comment]
Logging output from where the exception is thrown:
```
in _convert_attribute_ref:
cols:
[Column('id', Integer(), table=<input>, nullable=False), Column('x', Float(), table=<input>, nullable=False), Column('y', Float(), table=<input>, nullable=False), Column('z', Float(), table=<input>, nullable=False), Column('px', Integer(), table=<input>, nullable=False), Column('py', Integer(), table=<input>, nullable=False), Column('pz', Integer(), table=<input>, nullable=False), Column('ghost', Integer(), table=<input>, nullable=False)]
expr:
UnnamedAttributeRef(9, None)
input_scheme:
Scheme([(u'id', 'LONG_TYPE'), (u'x', 'DOUBLE_TYPE'), (u'y', 'DOUBLE_TYPE'), (u'z', 'DOUBLE_TYPE'), (u'px', 'LONG_TYPE'), (u'py', 'LONG_TYPE'), (u'pz', 'LONG_TYPE'), (u'ghost', 'LONG_TYPE'), (u'id1', 'LONG_TYPE'), (u'x1', 'DOUBLE_TYPE'), (u'y1', 'DOUBLE_TYPE'), (u'z1', 'DOUBLE_TYPE'), (u'px1', 'LONG_TYPE'), (u'py1', 'LONG_TYPE'), (u'pz1', 'LONG_TYPE'), (u'ghost1', 'LONG_TYPE')])
```

**Comment by bmyerz** [comment]
test for this bug is now in #492, and the fix is in https://github.com/uwescience/raco/tree/tipsy-fix-get-sql
